# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product__management.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 542)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/kfc-logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_headingText = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_headingText.setFont(font)
        self.label_headingText.setAlignment(QtCore.Qt.AlignCenter)
        self.label_headingText.setObjectName("label_headingText")
        self.verticalLayout.addWidget(self.label_headingText)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_productName = QtWidgets.QLabel(self.centralwidget)
        self.label_productName.setStyleSheet("color: #C41230;\n"
"font-size:30px;\n"
"padding: 5px")
        self.label_productName.setObjectName("label_productName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_productName)
        self.lineEdit_producName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_producName.setStyleSheet("border: 1px solid #C41230;\n"
"border-radius:10px;\n"
"font-size:30px;\n"
"padding:5px;")
        self.lineEdit_producName.setObjectName("lineEdit_producName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_producName)
        self.label_price = QtWidgets.QLabel(self.centralwidget)
        self.label_price.setStyleSheet("color: #C41230;\n"
"font-size:30px;\n"
"padding: 5px")
        self.label_price.setObjectName("label_price")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_price)
        self.doubleSpinBox_price = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_price.setStyleSheet("border: 1px solid #C41230;\n"
"border-radius:10px;\n"
"font-size:30px;\n"
"padding: 5px")
        self.doubleSpinBox_price.setObjectName("doubleSpinBox_price")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_price)
        self.label_imageURL = QtWidgets.QLabel(self.centralwidget)
        self.label_imageURL.setStyleSheet("color: #C41230;\n"
"font-size:30px;\n"
"padding: 5px")
        self.label_imageURL.setObjectName("label_imageURL")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_imageURL)
        self.lineEdit_imageURL = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_imageURL.setStyleSheet("border: 1px solid #C41230;\n"
"border-radius:10px;\n"
"font-size:30px;\n"
"padding: 5px")
        self.lineEdit_imageURL.setObjectName("lineEdit_imageURL")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_imageURL)
        self.label_description = QtWidgets.QLabel(self.centralwidget)
        self.label_description.setStyleSheet("color: #C41230;\n"
"font-size:30px;\n"
"padding: 5px")
        self.label_description.setObjectName("label_description")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_description)
        self.textEdit_description = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_description.setStyleSheet("border: 1px solid #C41230;\n"
"\n"
"font-size:30px;")
        self.textEdit_description.setObjectName("textEdit_description")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.textEdit_description)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_create = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_create.setFont(font)
        self.pushButton_create.setStyleSheet("background-color: #C41230;\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius:10px;\n"
"height:50px;\n"
"widht: 100px;\n"
"")
        self.pushButton_create.setObjectName("pushButton_create")
        self.verticalLayout.addWidget(self.pushButton_create)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KFC-Product Management"))
        self.label_headingText.setText(_translate("MainWindow", "Add New Product"))
        self.label_productName.setText(_translate("MainWindow", "Product Name"))
        self.label_price.setText(_translate("MainWindow", "Price"))
        self.label_imageURL.setText(_translate("MainWindow", "Picture:"))
        self.label_description.setText(_translate("MainWindow", "Description:"))
        self.pushButton_create.setText(_translate("MainWindow", "Create"))
import img_rc
